name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
change-template: "- $TITLE #$NUMBER [@$AUTHOR]"

categories:
  - title: "✨ Features"
    labels:
      - "feature"
      - "enhancement"
      - "✨"
      - "⚡️"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
      - "🐛"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
      - "📚"
  - title: " 🚨 Continous Integration"
    labels:
      - "testing"
      - "test"
  - title: " 🔨 Maintance"
    labels:
      - "Maintenance"

exclude-labels:
  - "changelog: skip"

template: |

  ## LangKit release v$NEXT_PATCH_VERSION
  🔍 LangKit: An open-source toolkit for monitoring Language Learning Models (LLMs). 📚 Extracts signals from prompts & responses, ensuring safety & security. 🛡️ Features include text quality, relevance metrics, & sentiment analysis. 📊 A comprehensive tool for LLM observability. 👀
  This version includes:

  $CHANGES
