name: langkit-ci

on:
  pull_request:
  push:
    branches: [main]
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  python-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.4.1
      - name: Set up python with poetry cache
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - run: echo 'python ${{ matrix.python-version }} poetry cache hit ${{ steps.setup-python.outputs.cache-hit }}'

      - name: Install dependencies
        run: poetry install
      - name: Configure whylogs
        run: mkdir ~/.whylogs && echo \"\" >> ~/.whylogs/disable_telemetry
      - name: Run pre-commit checks
        if: ${{ matrix.python-version == 3.8 }}
        run: poetry run pre-commit run --all-files
      - name: Run build
        run: poetry build
      - name: Run test
        run: poetry run pytest
